using System.Diagnostics.CodeAnalysis;

namespace Roster.Core.Domain
{
    public class Rank : AggregateRoot
    {
        [SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "Autogenerated by EF Core")]
        private int _id;

        private Rank(string name)
        {
            Name = name;
        }

        public RankId Id => new(_id);

        public string Name { get; }

        public static Rank Create(string name)
        {
            Rank rank = new(name);
            return rank;
        }
    }
}