create table members (
	id integer not null generated by default as identity primary key,
	name text
);

insert into members (name) values ('Henrik');
insert into members (name) values ('Clarke');
insert into members (name) values ('Highway');

create or replace function stream_members()
	returns trigger
	language plpgsql
as $$
declare
	notification json;
begin
	notification = json_build_object(
		'table', TG_TABLE_NAME,
		'action', TG_OP,
		'data', row_to_json(new)
	);
	
	perform pg_notify('members_stream', notification::text);
	return new;
end;
$$

create or replace trigger member_changes
before insert or update
on members
for each row
execute procedure stream_members();