START TRANSACTION;

DROP TABLE "Arma3Dlc";

CREATE TABLE "Dlcs" (
    "Name" text NOT NULL,
    CONSTRAINT "PK_Dlcs" PRIMARY KEY ("Name")
);

CREATE TABLE "OwnedDlc" (
    "ApplicationFormNickname" text NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_OwnedDlc" PRIMARY KEY ("ApplicationFormNickname", "Id"),
    CONSTRAINT "FK_OwnedDlc_ApplicationForms_ApplicationFormNickname" FOREIGN KEY ("ApplicationFormNickname") REFERENCES "ApplicationForms" ("Nickname") ON DELETE CASCADE
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211127073049_AddDlc', '5.0.9');

COMMIT;

insert into "Dlcs"
values ('Karts');

insert into "Dlcs"
values ('Helicopters');

insert into "Dlcs"
values ('Marksmen');

insert into "Dlcs"
values ('Apex');

insert into "Dlcs"
values ('Jets');

insert into "Dlcs"
values ('Malden');

insert into "Dlcs"
values ('Laws of War');

insert into "Dlcs"
values ('Tac-Ops');

insert into "Dlcs"
values ('Tanks');

insert into "Dlcs"
values ('Contact');

insert into "Dlcs"
values ('Art of War');

insert into "Dlcs"
values ('CSLA: Iron Curtain');

insert into "Dlcs"
values ('CSLA: Global Mobilization');

insert into "Dlcs"
values ('S.O.G. Prairie Fire');

insert into "Dlcs"
values ('Western Sahara');

commit;