START TRANSACTION;

CREATE TABLE "MemberDischarge" (
    "MemberNickname" text NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DateOfDischarge" timestamp with time zone NOT NULL,
    "DischargePath" integer NOT NULL,
    "Comment" text NULL,
    CONSTRAINT "PK_MemberDischarge" PRIMARY KEY ("MemberNickname", "Id"),
    CONSTRAINT "FK_MemberDischarge_Members_MemberNickname" FOREIGN KEY ("MemberNickname") REFERENCES "Members" ("Nickname") ON DELETE CASCADE
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211218081113_DischargeSystem', '6.0.1');

COMMIT;

